micro-manager/pymmcore

- .github/workflows/wheel.yml
We'll need to use something else for macOS to get the older SDKs.
> Simplify GitHub Actions build to Windows only

- .github/workflows/wheel-macos.yml
- maintainer-notes.md
- setup.py
It is likely that building on macOS 10.15 (the only version available with GitHub Actions) is actually safe -- to be tested.
> Build macOS wheels with GitHub Actions

- pyproject.toml
- setup.py
The `import numpy` in `setup.py` means that pip install (from source) from a clean env will fail.  Putting aside for the moment the challenges of building wheels anyway... how would you feel about adding this pyproject file that lets `pip install` attempt to build a wheel without numpy preinstalled?
> add pyproject.toml for pep517/518 builds

- .github/workflows/ubuntu.yml
It looks like update from pip 8.1.1 (found in GitHub Actions' Ubuntu 16.04 build environment) to pip 21.0.1 fails. Since the reason for having the Ubuntu build is solely to demonstrate that a manual build on Ubuntu works, there is probably no reason to keep 16.04. Instead, add the newly available 20.04 environment.
> Drop build test on Ubuntu 16.04; add 20.04

- .github/workflows/manylinux.yml
- .github/workflows/ubuntu.yml
- .github/workflows/win-mac.yml
- maintainer-notes.md
Hi @marktsuchida @nicost, would love to have py3.9 wheels for pymmcore on pypi.  Wheels built and worked fine for me locally on mac 10.15 and 11.1 with py3.9.1, and they appear to be [building fine on CI](https://github.com/tlambert-forks/pymmcore/actions/runs/548460189) in this PR.
It's not clear to me from the github workflow how you're actually deploying to PyPI (i.e. whether you're manually using twine?).  I could try to set up an auto-deploy action here too... but you'd need to add your twine API key to the repo secrets.  (or, if you prefer to just upload manually that's fine too).
thanks
> Build wheels for 3.9

- README.md
- maintainer-notes.md
- setup.cfg
- smoketest/smoke.py
The pymmcore version number now includes the device interface version.
Note that MMCore went from device interface version 69 to 70 while
keeping the MMCore version 10.1.1. This is relatively unusual, but
including the device interface version in the pymmcore version helps
working with this situation and is also probably generally helpful.
> Include device interface version in version number

- .gitignore
- MMCorePy.i
- pymmcore.i
- setup.py
Copy the SWIG `.i` file from mmCoreAndDevices, in preparation for its removal from mmCoreAndDevices.
See micro-manager/mmCoreAndDevices#10.
> Include SWIG interface file

- .github/workflows/win-mac.yml
Was getting error that newer version (4.0.2) is already installed.
> Remove version from Windows SWIG

- .github/workflows/build.yml
- maintainer-notes.md
NumPy (1.21.3 and later) does not provide wheels for 32-bit Windows for cp310, so let us also drop support.
> Exclude 32-bit Windows build for Python 3.10

- README.md
Just noticed:
https://github.com/conda-forge/pymmcore-feedstock
so adding install instructions
> add conda install instructions

- .github/workflows/build.yml
- README.md
NumPy does not provide 32-bit wheels for Python 3.10.
> Drop build for 32-bit Python 3.10 on Linux

- Dockerfile
The dockerfile was failing for two reasons:
1. Wasn't properly downloading the mmCoreAndDevices submodule
2. seems libboost is still needed
@marktsuchida is there any clever way we could change this to only include the democamera rather than every device adapter?
> fix: update dockerfile

- pymmcore/pymmcore_swig.i
So that `getMultiROI()` can be called.
Closes #78.
> Provide UnsignedVector bindings

- .github/workflows/build.yml
- README.md
- maintainer-notes.md
It reached EOL on 2023-06-27.
Also removed some old info (of only historic interest) from maintainer notes.
> Drop Python 3.7 support

- pymmcore/__init__.pyi
(No urgency for a new release here @marktsuchida)
This just adds a little convenience to the stubs, that lets you see the string literal value of the `g_` global strings without having to open up a terminal and print it, or look at the MMCore source code:
It does add the possibility that they go out of sync, but that's not a "new" problem for the stubs in general, and the "cost" is rather minimal (won't affect anything at runtime)
> add string literals to stub

- pymmcore/pymmcore_swig.i
> Propagate exceptions correctly from setSLMImage()

- pymmcore/__init__.pyi
- pymmcore/pymmcore_swig.i
This code should fix issues with `setSLMImage()`. Until now, images had to be converted to `char *` which lead to issues with values > `'\x7f'` (127) because they don't match to valid ASCII characters [(see discussion)](https://github.com/micro-manager/pymmcore/issues/86#issuecomment-1749232281). For the `genericSLMDevice`, this meant that gray is the brightest color that could be achieved. Allowing for `np.arrays` removes one data conversion step for the user, and matches the behaviour of pycro-manager.
**Accepted inputs with this PR:**
- 8bit grayscale [h,w] of type `uint8`
- 8bit RGB [h,w,c]  of type `uint8`, color order [RGB]
- As previously: `char *` with either w\*h bytes or w\*h\*4 bytes (for imgRGB32), so that existing scripts are not broken.
**Input formats I chose _not_ to …
> `setSLMImage()` with `np.arrays`

- pymmcore/__init__.pyi
I forgot to add the three DeviceInitializationState enums to the stubs.   Also taking the opportunity to add literal values to various enums, and arrange them better. 
(no need for new release here ... just for whenever the next one is)
> Add DeviceInitializationState enums to stubs, add literal values

- pymmcore/pymmcore_swig.i
- setup.py
Before this change, SWIG would pick up MMCore/MMDevice headers from an mmCoreAndDevices directory outside of the pymmcore directory, if present. This is because SWIG's search path for `%include` contains the current directory before any directories given by `-I` flags (so `%include "../mmCoreAndDevices/..."` was problematic).
Includes by the compiler (`#include`) may not have this problem but let's use the same method.
> Set include path in build script, not source

- setup.py
These are no longer needed with MMCore 11.
> Remove unnecessary system dependencies

- .github/workflows/ci.yml
- setup.py
Some compiler flags got dropped during the switch to cibuildwheel, so re-add them:
- On Linux (CI only, not in default), remove debug information from the binary (this should restore the ~1 MiB wheels instead of the ~11 MiB we currently get)
- On macOS and Linux, set the default symbol visibility to hidden
- On macOS and Linux, suppress the noisy warnings from MMCore (exception specifiers) and SWIG (unused variables)
- Also reposition where `CFLAGS` is inserted into the command line so that the default flags can be overridden
None of these are necessary for correct functioning, so the binaries built without them are okay.
> Re-add compiler and linker flags

- maintainer-notes.md
- pyproject.toml
So that a system-installed SWIG is not required for building locally.
> Use SWIG from PyPI as build requirement

- maintainer-notes.md
- pyproject.toml
found this nifty package: https://github.com/scipy/oldest-supported-numpy
makes it easier to declare numpy versions to build against
> build: uses oldest-supported-numpy in build requires

- pyproject.toml
(But was correct in the classifiers, so PyPI was displaying LPGL correctly.)
> License was wrong in pyproject.toml

- MANIFEST.in
- setup.py
This pulls in the changes up to https://github.com/micro-manager/mmCoreAndDevices/pull/435 and updates the preprocessor macros in setup.py accordingly:
- `MODULE_EXPORTS` removed from MMDevice build (this was previously needed to compile on Windows, even though semantically wrong)
- `MMDEVICE_CLIENT_BUILD` added to entire build
- `WIN32` and `_WINDOWS` removed, as these are no longer depended on by MMDevice/MMCore source
- `MMDEVICE_NO_GETTIMEOFDAY` removed, as MMDevice removed `gettimeofday()`
- `NOMINMAX` added on Windows, as MMCore (theoretically) requires it
---
> Upgrade MMDevice/MMCore and fix macro defs

- pyproject.toml
- setup.py
Recent versions of SWIG warn when -py3 is given.
> Require SWIG 4.1 and use -python, not -py3

- .github/workflows/ci.yml
- pyproject.toml
- src/pymmcore/pymmcore_swig.i
closes #113 
note that  https://github.com/scipy/oldest-supported-numpy is now deprecated
numpy has better docs and general support for [depending on numpy at build time](https://numpy.org/devdocs/dev/depending_on_numpy.html#adding-a-dependency-on-numpy) ... and this follows the advice there, namely:
- builds with `"numpy>=2.0.0b1; python_version>='3.9'",`
- `dependencies = ["numpy>=1.23.5"]`
- for python 3.8, we use the current pinnings
> support numpy2.0, require `numpy>=1.23.5`, add CI test

- src/pymmcore/__init__.pyi
There are lots of strings used throughout the CMMCore API, but using the wrong type of string in the wrong place can raise exceptions.  This PR clarifies those string names using type hints.  At the moment, I'm actually using `NewType`, but may relax that before this merges.  (NewType actually triggers a static typing error if you use anything other than the actual newtype, which is rather strict, but ensures safety).  A safer intermediate would be to use NewType for string types in return values, but use `TypeAlias` strings for parameters used as inputs
> clarify string types in pyi

- .github/workflows/ci.yml
This (compared to using the latest VS2022, as we currently do) increases the chance that pymmcore will work with whatever version of the C++ runtime that gets loaded (possibly by other modules imported before us). It may also help with installed by pip into a Conda environment, though that is not a recommended use case.
~Hopefully~ closes #119.
> CI: build with VS2019 toolset for Windows

- .github/workflows/ci.yml
- README.md
- pyproject.toml
curious to see whether it fails.  
for some reason, I'm currently unable to build pymmcore with any version of python locally on my mac:
```python
* Building wheel...
No `packages` or `py_modules` configuration, performing automatic discovery.
`src-layout` detected -- analysing ./src
discovered packages -- ['pymmcore']
discovered py_modules -- []
running bdist_wheel
running build
running build_py
running build_ext
running build_clib
building 'MMDevice' library
creating build/temp.macosx-11.0-arm64-cpython-312/mmCoreAndDevices/MMDevice
clang++ -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /Users/talley/miniforge3/envs/py312/include -arch arm64 -fPIC -O2 -isystem /Users/talley/miniforge3/envs/py312/include -arch arm64 -DMMDEVICE_CLIENT_BUILD -ImmCoreAndDevices/MMDevice -c …
```
> build: support python 3.13, drop python 3.8

- .github/dependabot.yml
- .github/workflows/ci.yml
- pyproject.toml
Im trying figure out why python 3.13 wheels didn't get added to PyPI when the action ran on Oct 7: https://github.com/micro-manager/pymmcore/actions/runs/11220032864/job/31187312757#step:4:300
as far as I can tell, everything in the action and pyproject.toml look good.  So my best guess/hope is that python 3.13, which was released that same day, simply wasn't available for download when cibuildwheel looked for it.  I think that running it again might fix it, but this PR just adds verbosity to cibuildwheel, updates its version, and adds dependabot updates to our github actions
closes #125
> ci: bump version of cibuildwheel

- src/pymmcore/__init__.pyi
Allow `None` to unregistered the callback.
> Fix type annotation for registerCallback
